### ISSUE TITLE
TypeError in buttonHitCallback

### ISSUE THREAD

**Issue by thundernixon** [thomgb/PDFButtonSpace#4]
Thanks so much to @arialcrime and @thomgb for making and updating this!

However, I'm still running into one issue with the update. When I try to export a PDF, I get the following error in my output window:

```
Traceback (most recent call last):
​  File "/Applications/RoboFont3.2.app/Contents/Resources/lib/python3.6/vanilla/vanillaBase.py", line 220, in action_
    self.callback(sender)
  File "AddButtonPDFToSC.py", line 174, in buttonHitCallback
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

Am I missing a step, or is this something that might be fixable in the script?

**Comment by arialcrime** [comment]
Can’t say I am surprised that my stale fix didn’t address that, sorry. 😂

**Comment by thundernixon** [comment]
Yup, I can’t blame you at all! I'm guessing something in RoboFont has changed since the initial PR. Thanks for contributing to this!

For now, I found another way to get the space center  PDF I need(mostly just [using the mojo UI function, plus some file handling stuff](https://github.com/thundernixon/quick-proofs/blob/master/space-center-to-cloud-pdf.py)), so I'm not in a rush to have this fixed. Just wanted to document the current issue.
